### PR TITLE
fix: use https for gitea

### LINKED ISSUE #113: Use https both internally and externally when using Gitea
Right now, the idpbuilder uses the local http connection on port 8880 when interacting with Gitea. This is where both http and https are available for Gitea and we use https over 8443 for all other services (backstage, argo, etc).

We should make it consistent with the rest of the services, and access everything over https. It is fine to use `skipVerify` when configuring the local go client for git in the idpbuilder code to connect to gitea.

### PR DESCRIPTION
**Pull request by nimakaviani**
- enable skipTLSVerify
- fix documentation

closes #113

### CODE REVIEW

File: pkg/controllers/gitrepository/controller.go [hunk 1]
```diff
@@ -13,7 +15,7 @@ import (
 	"github.com/cnoe-io/idpbuilder/pkg/util"
 	"github.com/go-git/go-git/v5"
 	"github.com/go-git/go-git/v5/plumbing/object"
-	"github.com/go-git/go-git/v5/plumbing/transport/http"
+	gohttp "github.com/go-git/go-git/v5/plumbing/transport/http"
```
Comment (nabuskey) [inline pkg/controllers/gitrepository/controller.go:18]: Why name it `gohttp`? Should be something like `gogithttp` if you want to be explicit.

**Review by nabuskey — APPROVED** [review]

File: pkg/controllers/gitrepository/controller.go (hunk 1 above)
Comment (nimakaviani) [reply pkg/controllers/gitrepository/controller.go]: fixed.
